var lang = {
    'no_talk_yet': 'Tema nu a inceput inca',
    'another_talk_is_on': 'Exista deja o tema in curs de cronometrare!',
    'video_display_disabled': 'Afisarea video este dezactivata! Te rugam sa o activezi.',
    'default_title': 'Titlu implicit',
    'start_meeting': 'Incepe intrunire',
    'end_meeting': 'Incheie intrunire',
    'file_not_exists_or_error': 'Fisierul nu exista sau a aparut o alta eroare',
    'musical_prelude': 'Preludiu muzical',
    'playing_musical_prelude': 'Preludiul muzical ruleaza...',
    'another_song_playing': 'Exista deja o melodie in curs de redare!',
    'weekend_meeting': 'Intrunirea din weekend',
    'weekday_meeting': 'Intrunirea din cursul saptamanii',
    'songs': 'Cantari',
    'video': 'Materiale video',
    'displays': 'Control monitoare',
    'select_display_for_prelude': 'Monitorul pt. afisaj preludiu',
    'select_display_for_timer': 'Monitor pt afisaj cronomentru',
    'select_display_for_video': 'Monitor pt afisaj materilae video',
    'activate_on_display_nr': 'Activeaza pe monitorul nr.',
    'deactivate_prelude_display': 'Dezactiveaza afisajul pentru preludiu',
    'deactivate_timer_display': 'Dezactiveaza afisajul pentru cronomentru',
    'deactivate_video_display': 'Dezactiveaza afisajul pentru video',
    'debt_time': 'Surplus de timp',
    'start_the_meeting_counter': 'Pentru a putea cronometra o tema, porneste cronometrul pentru intrunire ("Incepe intrunire")!',
    'recalculate_time': 'Recalculeaza automat timpii temelor',
    'settings': 'Setari',
    'disabled': 'Dezactivat',
    'title': 'Titlu',
    'duration': 'Durata',
    'flexible': 'Flexibil',
    'invisible': 'Neafisat',
    'save': 'Salveaza',
    'reset': 'Reseteaza',
    'prepare_finish_talk': 'Pregateste-te sa inchei tema!',
    'please_finish_the_talk': 'Te rugam, incheie tema!',
    'play_avi_songs': 'Ruleaza cantarile in mod avi',
    'changes_saved': 'Modificarile au fost salvate!',
    'images_and_pdf': 'Imagini si fisiere PDF',
    'show_prelude_display': 'Afiseaza ecran preludiu',
    //'prelude_window_title': 'Vă rugăm să vă ocupaţi locurile!',
    'prelude_window_title': 'Va rugam sa va ocupati locurile!',
    'prelude_countdown': 'Durata numaratoare inversa',
    'mins': 'min.',
    'internet_source': 'Preia lista teme online',
};
