var lang = {
    'no_talk_yet': 'Tema nu a inceput inca',
    'another_talk_is_on': 'Exista deja o tema in curs de cronometrare!',
    'video_display_disabled': 'Afisarea video este dezactivata! Te rugam sa o activezi.',
    'start_meeting': 'Incepe intrunire',
    'end_meeting': 'Incheie intrunire',
    'file_not_exists_or_error': 'Fisierul nu exista sau a aparut o alta eroare',
    'musical_prelude': 'Preludiu muzical',
    'playing_musical_prelude': 'Preludiul muzical ruleaza...',
    'another_song_playing': 'Exista deja o melodie in curs de redare!',
    'weekend_meeting': 'Intrunirea din weekend',
    'weekday_meeting': 'Intrunirea din cursul saptamanii',
    'songs': 'Cantari',
    'video': 'Materiale video',
    'displays': 'Control monitoare',
    'select_display_for_prelude': 'Monitorul pt. afisaj preludiu',
    'select_display_for_timer': 'Monitor pt afisaj cronomentru',
    'select_display_for_video': 'Monitor pt afisaj materilae video',
    'activate_on_display_nr.': 'Activeaza pe monitorul nr.',
    'deactivate_prelude_display': 'Dezactiveaza afisajul pentru preludiu',
    'deactivate_timer_display': 'Dezactiveaza afisajul pentru cronomentru',
    'deactivate_video_display': 'Dezactiveaza afisajul pentru video',
    'debt_time': 'Surplus de timp',
}
